name = "batteries"
testDriver = "BatteriesTest"
lintDriver = "runLinter"
defaultTargets = ["Batteries", "runLinter", "ProjectFormat"]

[[require]]
name = "PrettyFormat"
git = "https://github.com/frit007/lean-formatter"
rev = "main"

[leanOptions]
linter.missingDocs = true

[[lean_lib]]
name = "Batteries"

[[lean_lib]]
name = "BatteriesTest"
globs = ["BatteriesTest.+"]
leanOptions = {linter.missingDocs = false}

[[lean_exe]]
name = "runLinter"
srcDir = "scripts"
supportInterpreter = true

[[lean_exe]]
name = "ProjectFormat"
root = "ProjectFormat"
supportInterpreter = true

[[lean_exe]]
name = "test"
srcDir = "scripts"
